--*********************************************************
--         ORACLE SCRIPT TO CREATE DATA TABLES
--           SNM - 8/19/2008
--**********************************************************

CREATE TABLE ENCOUNTER_MAPPING ( 
    ENCOUNTER_IDE       	VARCHAR2(200) NOT NULL,
    ENCOUNTER_IDE_SOURCE	VARCHAR2(50) NOT NULL,
    ENCOUNTER_NUM       	NUMBER(38,0) NOT NULL,
    PATIENT_IDE         	VARCHAR2(200) ,
    PATIENT_IDE_SOURCE  	VARCHAR2(50) ,
    ENCOUNTER_IDE_STATUS	VARCHAR2(50) ,
    UPDATE_DATE             DATE ,
    UPLOAD_DATE         	DATE ,
    DOWNLOAD_DATE       	DATE ,
	IMPORT_DATE			    DATE ,
    SOURCESYSTEM_CD     	VARCHAR2(50) ,
	UPLOAD_ID           	NUMBER(38,0) ,
    CONSTRAINT ENCOUNTER_MAPPING_PK PRIMARY KEY(ENCOUNTER_IDE,ENCOUNTER_IDE_SOURCE)
 )
;
CREATE INDEX EM_UPLOADID_IDX ON ENCOUNTER_MAPPING(UPLOAD_ID)
;
CREATE  INDEX EM_IDX_ENCPATH ON ENCOUNTER_MAPPING(ENCOUNTER_IDE,ENCOUNTER_IDE_SOURCE,PATIENT_IDE,PATIENT_IDE_SOURCE,ENCOUNTER_NUM )
;
CREATE INDEX EM_ENCNUM_IDX ON ENCOUNTER_MAPPING(ENCOUNTER_NUM)
;

-- create Encounter_Mapping table with clustered PK on encounter_ide, encounter_ide_source */
CREATE TABLE PATIENT_MAPPING ( 
    PATIENT_IDE       	VARCHAR2(200) NOT NULL,
    PATIENT_IDE_SOURCE	VARCHAR2(50) NOT NULL,
    PATIENT_NUM       	NUMBER(38,0) NOT NULL,
    PATIENT_IDE_STATUS	VARCHAR2(50) ,
    UPLOAD_DATE       	DATE ,
    UPDATE_DATE             DATE ,
    DOWNLOAD_DATE     	DATE ,
    IMPORT_DATE			DATE,
    SOURCESYSTEM_CD   	VARCHAR2(50) ,
    UPLOAD_ID         	NUMBER(38,0) ,
    CONSTRAINT PATIENT_MAPPING_PK PRIMARY KEY(PATIENT_IDE,PATIENT_IDE_SOURCE)
 )
;
CREATE INDEX PM_UPLOADID_IDX ON PATIENT_MAPPING(UPLOAD_ID)
;
CREATE INDEX PM_PATNUM_IDX ON PATIENT_MAPPING(PATIENT_NUM)
;
CREATE INDEX PM_ENCPNUM_IDX ON 
PATIENT_MAPPING(PATIENT_IDE,PATIENT_IDE_SOURCE,PATIENT_NUM) ;

-- create Code_Lookup table with clustered PK on table_cd, column_cd, code_cd 
CREATE TABLE CODE_LOOKUP ( 
	TABLE_CD            VARCHAR2(100) NOT NULL,
	COLUMN_CD           VARCHAR2(100) NOT NULL,
	CODE_CD             VARCHAR2(50) NOT NULL,
	NAME_CHAR           VARCHAR2(650) NULL ,
	LOOKUP_BLOB			CLOB ,
    UPLOAD_DATE       	DATE NULL,
    UPDATE_DATE     	DATE NULL,
	DOWNLOAD_DATE   	DATE NULL,
	IMPORT_DATE     	DATE NULL,
	SOURCESYSTEM_CD 	VARCHAR2(50) NULL,
	UPLOAD_ID       	NUMBER(38,0) NULL ,
    CONSTRAINT CODE_LOOKUP_PK PRIMARY KEY(TABLE_CD,COLUMN_CD,CODE_CD)
	)
;
-- add index on name_char field 
CREATE INDEX CL_IDX_NAME_CHAR ON CODE_LOOKUP(name_char)
;
CREATE INDEX CL_IDX_UPLOADID ON CODE_LOOKUP(UPLOAD_ID)
;

-- create concept_dimension table with clustered PK on concept_path 
CREATE TABLE CONCEPT_DIMENSION ( 
	CONCEPT_CD          VARCHAR2(500) NOT NULL,
	CONCEPT_PATH    	VARCHAR2(700) NOT NULL,
	NAME_CHAR       	VARCHAR2(2000) NULL,
	CONCEPT_BLOB        CLOB NULL,
	UPDATE_DATE         DATE NULL,
	DOWNLOAD_DATE       DATE NULL,
	IMPORT_DATE         DATE NULL,
	SOURCESYSTEM_CD     VARCHAR2(50) NULL,
	UPLOAD_ID       	NUMBER(38,0) NULL,
    CONSTRAINT CONCEPT_DIMENSION_PK PRIMARY KEY(CONCEPT_PATH)
	)
;	
CREATE INDEX CD_UPLOADID_IDX ON CONCEPT_DIMENSION(UPLOAD_ID)
;
-- create observation_fact table with NONclustered PK on encounter_num,concept_cd,provider_id,start_date,modifier_cd  
CREATE TABLE OBSERVATION_FACT (
	ENCOUNTER_NUM   	NUMBER(38,0) NOT NULL,
	PATIENT_NUM     	NUMBER(38,0) NOT NULL,
	CONCEPT_CD      	VARCHAR2(50) NOT NULL,
	PROVIDER_ID     	VARCHAR2(50) NOT NULL,
	START_DATE      	DATE NOT NULL,
	MODIFIER_CD     	VARCHAR2(100) NOT NULL,
	VALTYPE_CD      	VARCHAR2(50) NULL,
	TVAL_CHAR       	VARCHAR2(255) NULL,
	NVAL_NUM        	NUMBER(18,5) NULL,
	VALUEFLAG_CD    	VARCHAR2(50) NULL,
	QUANTITY_NUM    	NUMBER(18,5) NULL,
	INSTANCE_NUM	    NUMBER(18,0) NULL,
	UNITS_CD        	VARCHAR2(50) NULL,
	END_DATE        	DATE NULL,
	LOCATION_CD     	VARCHAR2(50) NULL,
	CONFIDENCE_NUM  	NUMBER(18,5) NULL,
	OBSERVATION_BLOB	CLOB NULL,
	UPDATE_DATE     	DATE NULL,
	DOWNLOAD_DATE   	DATE NULL,
	IMPORT_DATE     	DATE NULL,
	SOURCESYSTEM_CD 	VARCHAR2(50) NULL,
	UPLOAD_ID       	NUMBER(38,0) NULL, 
    CONSTRAINT OBSERVATION_FACT_PK PRIMARY KEY(ENCOUNTER_NUM,CONCEPT_CD,PROVIDER_ID,START_DATE,MODIFIER_CD)
)
;



CREATE INDEX FACT_NOLOB ON OBSERVATION_FACT
(PATIENT_NUM, START_DATE, 
CONCEPT_CD, ENCOUNTER_NUM, NVAL_NUM, 
TVAL_CHAR, VALTYPE_CD, 
MODIFIER_CD, VALUEFLAG_CD, 
PROVIDER_ID, 
QUANTITY_NUM, 
UNITS_CD, 
END_DATE, 
LOCATION_CD, 
CONFIDENCE_NUM, 
UPDATE_DATE, 
DOWNLOAD_DATE, 
IMPORT_DATE, 
SOURCESYSTEM_CD, 
UPLOAD_ID)
;



CREATE INDEX FACT_CNPT_PAT_ENCT_IDX ON OBSERVATION_FACT
(CONCEPT_CD, PATIENT_NUM, ENCOUNTER_NUM) 
;

CREATE INDEX FACT_PATCON_DATE_PRVD_IDX ON OBSERVATION_FACT
(PATIENT_NUM, CONCEPT_CD, START_DATE, END_DATE, ENCOUNTER_NUM, 
PROVIDER_ID, NVAL_NUM, VALTYPE_CD) 
;


-- create Patient_Dimension table with clustered PK on patient_num */	
CREATE TABLE PATIENT_DIMENSION ( 
	PATIENT_NUM      	NUMBER(38,0) NOT NULL,
	VITAL_STATUS_CD  	VARCHAR2(50) NULL,
	BIRTH_DATE       	DATE NULL,
	DEATH_DATE       	DATE NULL,
	SEX_CD           	VARCHAR2(50) NULL,
	AGE_IN_YEARS_NUM 	NUMBER(38,0) NULL,
	LANGUAGE_CD      	VARCHAR2(50) NULL,
	RACE_CD          	VARCHAR2(50) NULL,
	MARITAL_STATUS_CD	VARCHAR2(50) NULL,
	RELIGION_CD      	VARCHAR2(50) NULL,
	ZIP_CD           	VARCHAR2(10) NULL,
	STATECITYZIP_PATH	VARCHAR2(700) NULL,
	PATIENT_BLOB     	CLOB NULL,
	UPDATE_DATE      	DATE NULL,
	DOWNLOAD_DATE    	DATE NULL,
	IMPORT_DATE      	DATE NULL,
	SOURCESYSTEM_CD  	VARCHAR2(50) NULL,
	UPLOAD_ID        	NUMBER(38,0) NULL ,
    CONSTRAINT PATIENT_DIMENSION_PK PRIMARY KEY(PATIENT_NUM)
	)
;
-- add indexes on additional Patient_Dimension fields 
CREATE  INDEX PD_IDX_DATES ON Patient_Dimension(Patient_Num, Vital_Status_Cd, Birth_Date, Death_Date)
;
CREATE  INDEX PD_IDX_AllPatientDim ON Patient_Dimension(Patient_Num, Vital_Status_Cd, Birth_Date, Death_Date, Sex_Cd, Age_In_Years_Num, Language_Cd, Race_Cd, Marital_Status_Cd, Religion_Cd, Zip_Cd)
;
CREATE  INDEX PD_IDX_StateCityZip ON Patient_Dimension (StateCityZip_Path, Patient_Num)
;
CREATE INDEX PATD_UPLOADID_IDX ON PATIENT_DIMENSION(UPLOAD_ID)
;
-- create Provider_Dimension table with clustered PK on provider_path, provider_id 	
CREATE TABLE PROVIDER_DIMENSION ( 
	PROVIDER_ID         VARCHAR2(50) NOT NULL,
	PROVIDER_PATH       VARCHAR2(700) NOT NULL,
	NAME_CHAR       	VARCHAR2(850) NULL,
	PROVIDER_BLOB       CLOB NULL,
	UPDATE_DATE     	DATE NULL,
	DOWNLOAD_DATE       DATE NULL,
	IMPORT_DATE         DATE NULL,
	SOURCESYSTEM_CD     VARCHAR2(50) NULL,
	UPLOAD_ID        	NUMBER(38,0) NULL ,
    CONSTRAINT  PROVIDER_DIMENSION_PK PRIMARY KEY(PROVIDER_PATH,provider_id)
	)
;
-- add index on provider_id, name_char 
CREATE INDEX PD_IDX_NAME_CHAR ON Provider_Dimension(Provider_Id,name_char)
;
CREATE INDEX PROD_UPLOADID_IDX ON Provider_Dimension(UPLOAD_ID)
;
-- create Visit_Dimension table with clustered PK on encounter_num 	
CREATE TABLE VISIT_DIMENSION ( 
	ENCOUNTER_NUM       NUMBER(38,0) NOT NULL,
	PATIENT_NUM         NUMBER(38,0) NOT NULL,
    ACTIVE_STATUS_CD    VARCHAR2(50) NULL,
	START_DATE          DATE NULL,
	END_DATE            DATE NULL,
	INOUT_CD            VARCHAR2(50) NULL,
	LOCATION_CD         VARCHAR2(50) NULL,
	LOCATION_PATH  	    VARCHAR2(900) NULL,
	VISIT_BLOB      	CLOB NULL,
	UPDATE_DATE         DATE NULL,
	DOWNLOAD_DATE       DATE NULL,
	IMPORT_DATE         DATE NULL,
	SOURCESYSTEM_CD     VARCHAR2(50) NULL,
	UPLOAD_ID       	NUMBER(38,0) NULL , 
    CONSTRAINT  VISIT_DIMENSION_PK PRIMARY KEY(ENCOUNTER_NUM,PATIENT_NUM)
	)
;

-- add indexes on addtional visit_dimension fields 

CREATE  INDEX VD_UPLOADID_IDX ON Visit_Dimension(UPLOAD_ID)
;


CREATE INDEX VISITDIM_EN_PN_LP_IO_SD_IDX ON VISIT_DIMENSION
(ENCOUNTER_NUM, PATIENT_NUM, LOCATION_PATH, INOUT_CD, START_DATE,END_DATE)
;


CREATE INDEX VISITDIM_STD_EDD_IDX ON VISIT_DIMENSION
(START_DATE, END_DATE)
;





