
package com.phaseforward.informadapter.odm._1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.phaseforward.adapterframework.export._1.RequestParams;
import com.phaseforward.adapterframework.export._1.RetrieveDataResult;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "InFormODMSoap", targetNamespace = "http://www.phaseforward.com/InFormAdapter/ODM/1.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.phaseforward.informadapter.odm._1.ObjectFactory.class,
    com.phaseforward.informadapter.odm._2.ObjectFactory.class,
    org.cdisc.ns.odm.v1.ObjectFactory.class,
    org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_secext_1_0.ObjectFactory.class,
    org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_utility_1_0.ObjectFactory.class,
    org.w3._2000._09.xmldsig_.ObjectFactory.class,
    com.phaseforward.informadapter.odm.extensions._2.ObjectFactory.class,
    com.phaseforward.adapterframework.export._1.ObjectFactory.class
})
public interface InFormODMSoap {


    /**
     * Gets InForm metadata in ODM format
     * 
     * @param node
     * @return
     *     returns com.phaseforward.informadapter.odm._1.DownloadMetadataODMResult
     */
    @WebMethod(operationName = "DownloadMetadataODM", action = "http://www.phaseforward.com/InFormAdapter/ODM/1.0/DownloadMetadataODM")
    @WebResult(name = "DownloadMetadataODMResult", targetNamespace = "http://www.phaseforward.com/InFormAdapter/ODM/1.0", partName = "DownloadMetadataODMResult")
    public DownloadMetadataODMResult downloadMetadataODM(
        @WebParam(name = "node", targetNamespace = "http://www.phaseforward.com/InFormAdapter/ODM/1.0", partName = "node")
        Node node);

    /**
     * Gets InForm admin edu.chip.carranet.data in ODM format
     * 
     * @param node
     * @return
     *     returns com.phaseforward.informadapter.odm._1.DownloadAdminDataODMResult
     */
    @WebMethod(operationName = "DownloadAdminDataODM", action = "http://www.phaseforward.com/InFormAdapter/ODM/1.0/DownloadAdminDataODM")
    @WebResult(name = "DownloadAdminDataODMResult", targetNamespace = "http://www.phaseforward.com/InFormAdapter/ODM/1.0", partName = "DownloadAdminDataODMResult")
    public DownloadAdminDataODMResult downloadAdminDataODM(
        @WebParam(name = "node", targetNamespace = "http://www.phaseforward.com/InFormAdapter/ODM/1.0", partName = "node")
        Node node);

    /**
     * Gets InForm patient in ODM format
     * 
     * @param node
     * @return
     *     returns com.phaseforward.informadapter.odm._1.DownloadPatientDataODMResult
     */
    @WebMethod(operationName = "DownloadPatientDataODM", action = "http://www.phaseforward.com/InFormAdapter/ODM/1.0/DownloadPatientDataODM")
    @WebResult(name = "DownloadPatientDataODMResult", targetNamespace = "http://www.phaseforward.com/InFormAdapter/ODM/1.0", partName = "DownloadPatientDataODMResult")
    public DownloadPatientDataODMResult downloadPatientDataODM(
        @WebParam(name = "node", targetNamespace = "http://www.phaseforward.com/InFormAdapter/ODM/1.0", partName = "node")
        Node node);

    /**
     * Gets list of sites for a trial
     * 
     * @param node
     * @return
     *     returns com.phaseforward.informadapter.odm._1.GetSiteListResult
     */
    @WebMethod(operationName = "GetSiteList", action = "http://www.phaseforward.com/InFormAdapter/ODM/1.0/GetSiteList")
    @WebResult(name = "GetSiteListResult", targetNamespace = "http://www.phaseforward.com/InFormAdapter/ODM/1.0", partName = "GetSiteListResult")
    public GetSiteListResult getSiteList(
        @WebParam(name = "node", targetNamespace = "http://www.phaseforward.com/InFormAdapter/ODM/1.0", partName = "node")
        Node node);

    /**
     * Gets list of patients for a site
     * 
     * @param node
     * @return
     *     returns com.phaseforward.informadapter.odm._1.GetPatientListResult
     */
    @WebMethod(operationName = "GetPatientList", action = "http://www.phaseforward.com/InFormAdapter/ODM/1.0/GetPatientList")
    @WebResult(name = "GetPatientListResult", targetNamespace = "http://www.phaseforward.com/InFormAdapter/ODM/1.0", partName = "GetPatientListResult")
    public GetPatientListResult getPatientList(
        @WebParam(name = "node", targetNamespace = "http://www.phaseforward.com/InFormAdapter/ODM/1.0", partName = "node")
        Node node);

    /**
     * Gets list of visits/forms for a patient
     * 
     * @param node
     * @return
     *     returns com.phaseforward.informadapter.odm._1.GetPatientFormsResult
     */
    @WebMethod(operationName = "GetPatientForms", action = "http://www.phaseforward.com/InFormAdapter/ODM/1.0/GetPatientForms")
    @WebResult(name = "GetPatientFormsResult", targetNamespace = "http://www.phaseforward.com/InFormAdapter/ODM/1.0", partName = "GetPatientFormsResult")
    public GetPatientFormsResult getPatientForms(
        @WebParam(name = "node", targetNamespace = "http://www.phaseforward.com/InFormAdapter/ODM/1.0", partName = "node")
        Node node);

    /**
     * Gets list of visits/forms for a patient
     * 
     * @param node
     * @return
     *     returns com.phaseforward.informadapter.odm._1.GetTransactionsResult
     */
    @WebMethod(operationName = "GetTransactions", action = "http://www.phaseforward.com/InFormAdapter/ODM/1.0/GetTransactions")
    @WebResult(name = "GetTransactionsResult", targetNamespace = "http://www.phaseforward.com/InFormAdapter/ODM/1.0", partName = "GetTransactionsResult")
    public GetTransactionsResult getTransactions(
        @WebParam(name = "node", targetNamespace = "http://www.phaseforward.com/InFormAdapter/ODM/1.0", partName = "node")
        Node node);

    /**
     * Gets the status of the ODM transaction interface
     * 
     * @param node
     * @return
     *     returns com.phaseforward.informadapter.odm._1.GetTransactionStatusResult
     */
    @WebMethod(operationName = "GetTransactionStatus", action = "http://www.phaseforward.com/InFormAdapter/ODM/1.0/GetTransactionStatus")
    @WebResult(name = "GetTransactionStatusResult", targetNamespace = "http://www.phaseforward.com/InFormAdapter/ODM/1.0", partName = "GetTransactionStatusResult")
    public GetTransactionStatusResult getTransactionStatus(
        @WebParam(name = "node", targetNamespace = "http://www.phaseforward.com/InFormAdapter/ODM/1.0", partName = "node")
        Node node);

    /**
     * Gets edu.chip.carranet.data using LSID values to determine what edu.chip.carranet.data is returned.
     * 
     * @param requestParams
     * @return
     *     returns com.phaseforward.adapterframework.export._1.RetrieveDataResult
     */
    @WebMethod(operationName = "RetrieveData", action = "http://www.phaseforward.com/AdapterFramework/Export/1.0/RetrieveData")
    @WebResult(name = "RetrieveDataResult", targetNamespace = "http://www.phaseforward.com/AdapterFramework/Export/1.0", partName = "RetrieveDataResult")
    public RetrieveDataResult retrieveData(
        @WebParam(name = "requestParams", targetNamespace = "http://www.phaseforward.com/AdapterFramework/Export/1.0", partName = "requestParams")
        RequestParams requestParams);

}
