/*
    Creates a temporary table for transaction reporting and updating I2B2 DB.
	THIS table is used in STEP 1 and STEP 2.
*/
CREATE TABLE TBLRSLTDATAIMPORT (
        STUDY NVARCHAR2(100),
	SUBJECTKEY NVARCHAR2(38) NULL,
	SITELOCATION NVARCHAR2(50) NULL,
	STUDYEVENT NVARCHAR2(50) NULL,
	STUDYEVENTREPEATKEY NVARCHAR2(100) NULL,
	FORM NVARCHAR2(100) NULL,
	ITEMGROUP NVARCHAR2(100) NULL,
	ITEMGROUPREPEATKEY NVARCHAR2(100) NULL,
	ITEM NVARCHAR2(100) NULL,
	VAL NVARCHAR2(100) NULL,
	ITEMLOCATION NVARCHAR2(100) NULL,
	DATETIMESTAMP NVARCHAR2(100) NULL,
	REASONFORCHANGE NVARCHAR2(1000) NULL,
	ODMCODE NVARCHAR2(100) NULL,
	ANSWER NVARCHAR2(100) NULL,
	TYPE NVARCHAR2(255) NULL,
	CONCEPTCODE NVARCHAR2(500) NULL,
	MODIFIER NVARCHAR2(100) NULL,
	LOCATION_PATH NVARCHAR2(50) NOT NULL,
	PATIENT_NUM NVARCHAR2(100) NULL,
	CONCEPT_CD NVARCHAR2(500) NULL,
	PROVIDER_ID NVARCHAR2(50) NOT NULL,
	START_DATE NVARCHAR2(50) NULL,
	MODIFIER_CD NVARCHAR2(100) NOT NULL,
	VALTYPE_CD NVARCHAR2(50) NULL,
	TVAL_CHAR VARCHAR2(255) NULL,
	NVAL_NUM NUMBER(18,5) NULL,
	VALUEFLAG_CD NVARCHAR2(50) NULL,
	SOURCESYSTEM_CD NVARCHAR2(50) NULL,
	ERRORDESCRIPTION NVARCHAR2(2000) NULL
    );

/* This table is used only in STEP 2 */
CREATE TABLE tmp_EncTable (
	ENCOUNTER_NUM NUMBER(38,0),
	PATIENT_NUM NVARCHAR2(100) NULL,
	LOCATION_PATH NVARCHAR2(50) NOT NULL,
	START_DATE DATE,
	END_DATE DATE,
	SOURCESYSTEM_CD NVARCHAR2(50) NULL,
	IsNewEncounter NUMBER(3,0) default 1
);