package edu.chip.carranet.auth;

import org.spin.query.message.identity.IdentityService;
import org.spin.query.message.identity.IdentityServiceException;
import org.spin.tools.crypto.signature.Identity;
import org.spin.tools.crypto.signature.XMLSignatureUtil;


/**
 * This is an identity service implementation that takes a user name
 * and the Carranet AuthString.  The AuthString will be generated by the AuthService/PMFacade
 * <p/>
 * AuthString = base64(unmarshal(sign(identity)))
 */
public class I2b2SSRIdentityService implements IdentityService {


    /**
     * @param domain   doesn't matter
     * @param username the username
     * @param password the authString
     * @return
     * @throws IdentityServiceException
     */
    @Override
    public Identity certify(String domain, String username, String password)
            throws IdentityServiceException {

        try {
            Identity id = new Identity(domain,username,password);
            XMLSignatureUtil.getDefaultInstance().sign(id);
            return id;

        } catch (Exception e) {
            throw new IdentityServiceException("Not authorized", e);
        }
    }
}
