# TOMCAT SERVERS
role :webserver, "carra-node-production",
     "carra-node-2-production",
     "carra-node-3-production",
     "carra-node-4-production",
     "carra-node-5-production",
     "carra-node-6-production",
     "carra-node-7-production",
     "carra-node-8-production",
     "carra-node-9-production",
     "carra-node-10-production",
     "carra-node-11-production",
     "carra-node-12-production",
     "carra-node-13-production",
     "carra-node-14-production",
     "carra-node-15-production",
     "carra-node-16-production",
     "carra-node-17-production",
     "carra-node-18-production",
     "carra-node-19-production",
     "carra-node-20-production",
     "carra-node-21-production",
     "carra-node-22-production",
     "carra-node-23-production",
     "carra-node-24-production",
     "carra-node-25-production",
     "carra-node-26-production",
     "carra-node-27-production",
     "carra-node-28-production",
     "carra-node-29-production",
     "carra-node-30-production",
     "carra-node-31-production",
     "carra-node-32-production",
     "carra-node-33-production",
     "carra-node-34-production",
     "carra-node-35-production",
     "carra-node-36-production",
     "carra-node-37-production",
     "carra-node-38-production",
     #"carra-node-39-production",
     "carra-node-40-production",
     "carra-node-41-production",
     "carra-node-42-production",
     "carra-node-43-production",
     "carra-node-44-production",
     "carra-node-45-production",
     "carra-node-46-production",
     "carra-node-47-production",
     "carra-node-48-production",
     "carra-node-49-production",
     "carra-node-50-production",
     "carra-node-51-production",
     "carra-node-52-production",
     "carra-node-53-production",
     "carra-node-54-production",
     "carra-node-55-production",
     "carra-node-56-production",
     "carra-node-57-production",
     "carra-node-58-production",
     "carra-node-59-production",
     "carra-node-60-production"

namespace :carra do
  desc "Push out shrine-config-production.xml"
  task :pushconfig do
    run "mkdir -p #{tomcat_home}conf/Catalina/localhost/"
    file = File.read("config/shrine-config-production.xml")
    put file, "#{tomcat_home}conf/Catalina/localhost/shrine-cell.xml"
  end
end
